# Generated by Django 3.1.3 on 2023-06-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('company', models.TextField()),
                ('precio', models.TextField()),
                ('country', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('dispositivo', models.TextField()),
                ('dificultad', models.TextField()),
                ('categoria', models.TextField()),
                ('version', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
